
version: "3"

services:
  web:
    build: ./game-stream-search-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
  app:
    build: ./game-stream-search-web
    ports:
      - "8080:8080"
    depends_on:
      - web