
version: "3"

services:
  web:
    build: ./game-stream-search-service
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "5000:5000"
  app:
    build: ./game-stream-search-web
    ports:
      - "8080:8080"
    depends_on:
      - web
  dynamodb-integration-tests:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./integration-tests/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal