AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ApplicationName:
    Type: String
    Description: This name will be used for the database

Resources:
  ChannelsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: 'Channels'
      BillingMode: PROVISIONED
      ProvisionedThroughput: 
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      AttributeDefinitions:
        -
          AttributeName: 'StreamPlatformName'
          AttributeType: 'S'
        -
          AttributeName: 'ChannelName'
          AttributeType: 'S'
        -
          AttributeName: 'DateRegistered'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'StreamPlatformName'
          KeyType: 'HASH'
        -
          AttributeName: 'ChannelName'
          KeyType: 'RANGE'
      LocalSecondaryIndexes:
        -
          IndexName: "DateRegisteredIndex"
          KeySchema:
            -
              AttributeName: 'StreamPlatformName'
              KeyType: 'HASH'
            -
              AttributeName: 'DateRegistered'
              KeyType: 'RANGE'
          Projection: 
            ProjectionType: 'ALL'

  DatabasePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: '${ApplicationName}-dynamodb-read-write'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:DescribeTable
              - dynamodb:BatchGetItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Resource:
              Fn::GetAtt: ChannelsTable.Arn

Outputs:
  DatabasePolicyName:
    Value:
      Ref: DatabasePolicy
    Export:
      Name: DatabasePolicyName

  
