AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ApplicationName:
    Type: String
    Description: The name of the Elastic beanstalk application
  EnvironmentCNAMEPrefix:
    Type: String
    Description: The name associated with the environment
  DeploymentBucketKey:
    Type: String
    Description: The S3 bucket key of deployable bundle

Resources:
  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName:
        Ref: ApplicationName

  ApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: Application
      SourceBundle:
        S3Bucket:
          Fn::ImportValue: EbDeploymentBucketName
        S3Key:
          Ref: DeploymentBucketKey

  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: Application
      CNAMEPrefix:
        Ref: EnvironmentCNAMEPrefix
      Description: The elastic beanstalk application environment
      Tier:
        Name: WebServer
        Type: Standard
      SolutionStackName: 64bit Amazon Linux 2 v3.2.0 running Docker
      OptionSettings:
        - Namespace: aws:ec2:instances
          OptionName: InstanceTypes
          Value: t2.micro
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value:
            Fn::ImportValue: EbServiceRoleName
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value:
            Fn::ImportValue: InstanceProfileName
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value:
            Fn::ImportValue: SecurityGroupName
      VersionLabel:
        Ref: ApplicationVersion


    

